# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      env:
      APP_NAME: Ranking.Api
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.0' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet publish $APP_NAME --configuration Release

    - uses: appleboy/scp-action@master
      env:
        HOST: srv03.mikr.us
        USERNAME: ${{ secrets.ssh_username }}
        PORT: ${{ secrets.ssh_port }}
        KEY: ${{ secrets.mikrus }}
      with:
        source: "$APP_NAME/bin/Release/netcoreapp2.0/publish"
        target: "/var/www/ranking"
        
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: srv03.mikr.us
        USERNAME:  ${{ secrets.ssh_username }}
        PORT:  ${{ secrets.ssh_port }} 
        KEY: ${{ secrets.mikrus }}
        script: |
         
         kill $(pgrep -f $APP_NAME)&
         dotnet /var/www/ranking/$APP_NAME/bin/Release/netcoreapp2.0/publish/$APP_NAME.dll >/dev/null &