name: Deploy to Mikrus

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.0' 
    - run: dotnet publish ${{ secrets.app_name }} -o ${{ secrets.app_name }} --configuration Release

    - uses: appleboy/scp-action@master
      env:
        HOST: srv03.mikr.us
        USERNAME: ${{ secrets.ssh_username }}
        PORT: ${{ secrets.ssh_port }}
        KEY: ${{ secrets.mikrus }}
      with:
        source: "./${{ secrets.app_name }}/${{ secrets.app_name }}/"
        target: "/var/www/"
        
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: srv03.mikr.us
        USERNAME:  ${{ secrets.ssh_username }}
        PORT:  ${{ secrets.ssh_port }} 
        KEY: ${{ secrets.mikrus }}
        script: |
         kill $(pgrep -f ${{ secrets.app_name }})&
         dotnet /var/www/${{ secrets.app_name }}/${{ secrets.app_name }}/${{ secrets.app_name }}.dll >/dev/null &