name: Deploy to Mikrus

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.0' 
    - run: dotnet publish Ranking.Web -o Ranking.Web --configuration Release

    - uses: appleboy/scp-action@master
      env:
        HOST: srv03.mikr.us
        USERNAME: ${{ secrets.ssh_username }}
        PORT: ${{ secrets.ssh_port }}
        KEY: ${{ secrets.mikrus }}
      with:
        source: "./Ranking.Web/Ranking.Web/"
        target: "/var/www/"
        
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: srv03.mikr.us
        USERNAME:  ${{ secrets.ssh_username }}
        PORT:  ${{ secrets.ssh_port }} 
        KEY: ${{ secrets.mikrus }}
        script: |
         kill $(pgrep -f Ranking.Web)&
         dotnet /var/www/Ranking.Web/Ranking.Web/Ranking.Web.dll >/dev/null &